networks:
  default:
    external:
      name: roboshop
services:
  # docker run -d --name mongodb --network=roboshop mongodb:1.0.0
  mongodb:
    image: mongodb:1.0.0
      # networks:
      # - roboshop
  catalogue:
    image:  catalogue:1.0.0
    depends_on:
    - mongodb
  web:
    image: web:1.0.0
    ports:
    - "80:80"
    depends_on:
    - catalogue
  redis:

  user:
    image: user:1.0.0
    depends_on:
    - redis
    - mongodb
  cart:
    image: cart:1.0.0
    depends_on:
    - redis
    - catalogue